language: common-lisp

sudo: true

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=allegro
    - LISP=abcl
    - LISP=ecl

matrix:
  allow_failures:
    - env: LISP=clisp
    - env: LISP=ecl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
  - cl -l prove
       -e '(or (prove:run :cl-cookie-test) (uiop:quit -1))'
